#!/bin/bash
tarname="pa99_olds"
mainclass="CC99"

# DELETE TAR / CLEAR STAGING
rm $tarname.tar
rm -R STAGING/*
# COPY EVERYTHING TO STAGING
cp src/main/java/*.java answer.txt -r input STAGING
cd STAGING
# TEST - compile / put in jar / delete .class / run
javac *.java -Xlint:deprecation -d .
jar -cvf TestJar.jar *.class
hadoop jar TestJar.jar $mainclass input output
# cat ./output/part-r-00000
# CREATE TAR
tar -cvf ../$tarname.tar *.java input output
cd ..